# PostgreSQL. Versions 8.2 and up are supported.
#

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: bootstrap-flatlab-theme_development
  username: <%= ENV['PG_DB_DEV_USER'] %>
  password: <%= ENV['PG_DB_DEV_PASS'] %>
  host: localhost
  port: 5432

test:
  <<: *default
  database: bootstrap-flatlab-theme_test
  username: <%= ENV['PG_DB_DEV_USER'] %>
  password: <%= ENV['PG_DB_DEV_PASS'] %>
  host: localhost
  port: 5432

production:
  <<: *default
  database: <%= ENV['BOOTSTRAP_FLATLAB_THEME_DB_PROD'] %>
  username: <%= ENV['BOOTSTRAP_FLATLAB_THEME_DB_USERNAME'] %>
  password: <%= ENV['BOOTSTRAP_FLATLAB_THEME_DB_PASSWORD'] %>
  host: <%= ENV['BOOTSTRAP_FLATLAB_THEME_DB_HOST'] %>
  port: <%= ENV['BOOTSTRAP_FLATLAB_THEME_DB_PORT'] %>
  